services:
  mediagarrd-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mediagarrd-server
    env_file:
      - ./dockerenv/server.env
    ports:
      - "38471:38471"
    volumes:
      - "./data/server/backups:/var/lib/mediagarrd/backups"
      - "/srv/jellyfin:/srv/sources/jellyfin:ro"
      - "/home/user/sonarr:/srv/sources/sonarr:ro"
    restart: unless-stopped
